#include "audio/AudioDecoder.h"
#include "audio/AudioDocument.h"
#include "audio/AudioLoadCoordinator.h"
#include <atomic>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <future>
#include <iostream>
#include <limits>
#include <thread>
#include <vector>
namespace { int failures=0;
#define CHECK(x) do { if(!(x)){std::cerr<<"FAILED: " #x "\n";++failures;} } while(false)
void U16(std::vector<unsigned char>&b,uint16_t v){b.push_back(static_cast<unsigned char>(v));b.push_back(static_cast<unsigned char>(v>>8));} void U32(std::vector<unsigned char>&b,uint32_t v){for(int i=0;i<4;++i)b.push_back(static_cast<unsigned char>(v>>(i*8)));} void Tag(std::vector<unsigned char>&b,const char*t){b.insert(b.end(),t,t+4);} void Patch(std::vector<unsigned char>&b,size_t o,uint32_t v){for(int i=0;i<4;++i)b[o+i]=static_cast<unsigned char>(v>>(i*8));}
void Chunk(std::vector<unsigned char>& b,const char*tag,const std::vector<unsigned char>&data){Tag(b,tag);U32(b,static_cast<uint32_t>(data.size()));b.insert(b.end(),data.begin(),data.end());if(data.size()&1U)b.push_back(0);}
std::vector<unsigned char> Fmt(uint16_t f,uint16_t c,uint32_t r,uint16_t bits,uint16_t align=0){std::vector<unsigned char>b;const auto a=align?align:static_cast<uint16_t>(c*(bits/8));U16(b,f);U16(b,c);U32(b,r);U32(b,r*a);U16(b,a);U16(b,bits);return b;}
std::vector<unsigned char> Wav(uint16_t f=1,uint16_t c=1,uint32_t r=48000,uint16_t bits=16,const std::vector<unsigned char>&data={},uint16_t align=0){std::vector<unsigned char>b;Tag(b,"RIFF");U32(b,0);Tag(b,"WAVE");Chunk(b,"fmt ",Fmt(f,c,r,bits,align));Chunk(b,"data",data);Patch(b,4,static_cast<uint32_t>(b.size()-8));return b;} void Write(const std::filesystem::path&p,const std::vector<unsigned char>&b){std::ofstream o(p,std::ios::binary);o.write(reinterpret_cast<const char*>(b.data()),static_cast<std::streamsize>(b.size()));}
bool Throws(const tokkebi::audio::DecodedPcm& pcm,uint64_t f,uint32_t c){try{static_cast<void>(pcm.At(f,c));return false;}catch(const std::out_of_range&){return true;}}
}
int main(){using namespace tokkebi::audio;const auto root=std::filesystem::temp_directory_path()/"tokkebi-p02-8-1-tests";std::error_code ec;std::filesystem::remove_all(root,ec);std::filesystem::create_directories(root,ec);
 const std::vector<unsigned char> p16{0,0x80,0,0,0,0x40,0xff,0x7f};auto wav=root/"fixture.wav";Write(wav,Wav(1,1,48000,16,p16));auto d=DecodeLocalAudio(wav);CHECK(d.Success());CHECK(d.info.frames==4&&d.info.sourceFormat==SampleFormat::Int16);CHECK(std::abs(d.audio.At(0,0)+1.f)<.001f);CHECK(std::abs(d.audio.At(3,0)-.999969f)<.001f);
 std::vector<unsigned char> p24{0,0,0x80,0,0,0,0xff,0xff,0x7f,0,0,0x40};auto p24path=root/"pcm24.wav";Write(p24path,Wav(1,2,44100,24,p24));auto d24=DecodeLocalAudio(p24path);CHECK(d24.Success()&&d24.info.channels==2&&d24.info.frames==2&&d24.info.sourceFormat==SampleFormat::Int24);CHECK(std::abs(d24.audio.At(0,0)+1.f)<.001f);
 std::vector<unsigned char> p32;U32(p32,0x80000000U);U32(p32,0x40000000U);U32(p32,0x7fffffffU);auto p32path=root/"pcm32.wav";Write(p32path,Wav(1,1,48000,32,p32));auto d32=DecodeLocalAudio(p32path);CHECK(d32.Success()&&d32.info.codec==AudioCodec::Pcm&&d32.info.sourceFormat==SampleFormat::Int32&&d32.info.frames==3);CHECK(std::abs(d32.audio.At(0,0)+1.f)<.001f&&std::abs(d32.audio.At(1,0)-.5f)<.001f&&d32.audio.At(2,0)>.99f);
 float quarter=.25f;std::vector<unsigned char> pf(sizeof(float));std::memcpy(pf.data(),&quarter,4);auto floatpath=root/"float.wav";Write(floatpath,Wav(3,1,48000,32,pf));auto df=DecodeLocalAudio(floatpath);CHECK(df.Success()&&df.info.sourceFormat==SampleFormat::Float32&&std::abs(df.audio.At(0,0)-.25f)<.001f);
 auto wrong=root/"wrong.bin";Write(wrong,Wav(1,1,48000,16,p16));CHECK(DecodeLocalAudio(wrong).Success());auto unicode=root/std::filesystem::u8path(u8"한글.wav");Write(unicode,Wav(1,1,48000,16,p16));CHECK(DecodeLocalAudio(unicode).Success());CHECK(DecodeLocalAudio(root/"missing.wav").error==DecodeErrorCode::FileNotFound);CHECK(DecodeLocalAudio(root).error==DecodeErrorCode::NotRegularFile);
 Write(root/"empty.wav",{});CHECK(DecodeLocalAudio(root/"empty.wav").error==DecodeErrorCode::TruncatedFile);std::vector<unsigned char> truncated{'R','I','F','F',6,0,0,0,'W','A','V','E',0,0};Write(root/"truncated.wav",truncated);CHECK(DecodeLocalAudio(root/"truncated.wav").error==DecodeErrorCode::TruncatedFile);auto noData=Wav();noData.resize(36);Patch(noData,4,28);Write(root/"nodata.wav",noData);CHECK(DecodeLocalAudio(root/"nodata.wav").error==DecodeErrorCode::CorruptFile);Write(root/"align.wav",Wav(1,1,48000,16,p16,1));CHECK(DecodeLocalAudio(root/"align.wav").error==DecodeErrorCode::InvalidMetadata);Write(root/"zero.wav",Wav());auto zero=DecodeLocalAudio(root/"zero.wav");CHECK(zero.Success()&&zero.info.frames==0);
 auto big=Wav(1,1,48000,16,p16);Patch(big,4,0xffffff00U);Write(root/"riff-big.wav",big);CHECK(DecodeLocalAudio(root/"riff-big.wav").error==DecodeErrorCode::TruncatedFile);auto small=Wav(1,1,48000,16,p16);Patch(small,4,4);Write(root/"riff-small.wav",small);CHECK(DecodeLocalAudio(root/"riff-small.wav").error==DecodeErrorCode::CorruptFile);
 std::vector<unsigned char> unknown;Tag(unknown,"RIFF");U32(unknown,0);Tag(unknown,"WAVE");Chunk(unknown,"JUNK",{1,2,3});Chunk(unknown,"fmt ",Fmt(1,1,48000,16));Chunk(unknown,"JNK2",{7,8});Chunk(unknown,"data",p16);Patch(unknown,4,static_cast<uint32_t>(unknown.size()-8));Write(root/"unknown.wav",unknown);CHECK(DecodeLocalAudio(root/"unknown.wav").Success());
 auto outside=Wav(1,1,48000,16,p16);Patch(outside,4,4);Write(root/"fmt-outside.wav",outside);CHECK(DecodeLocalAudio(root/"fmt-outside.wav").error==DecodeErrorCode::CorruptFile);Write(root/"unsupported.wav",Wav(1,1,48000,8,{0}));CHECK(DecodeLocalAudio(root/"unsupported.wav").error==DecodeErrorCode::UnsupportedFormat);Write(root/"aiff",{'F','O','R','M',0,0,0,0,'A','I','F','F'});CHECK(DecodeLocalAudio(root/"aiff").info.container==AudioContainer::Aiff);Write(root/"flac",{'f','L','a','C',0,0,0,0,0,0,0,0});CHECK(DecodeLocalAudio(root/"flac").info.container==AudioContainer::Flac);
 DecodedAllocation alloc;CHECK(CalculateDecodedAllocation(10,1,alloc)&&alloc.sampleCount==10&&alloc.bytes==40);CHECK(CalculateDecodedAllocation(10,2,alloc)&&alloc.sampleCount==20);CHECK(!CalculateDecodedAllocation(std::numeric_limits<uint64_t>::max(),2,alloc));CHECK(!CalculateDecodedAllocation(kMaximumDecodedBytes/4+1,1,alloc));CHECK(!CalculateDecodedAllocation(1,0,alloc));CHECK(!Throws(d.audio,0,0)&&Throws(d.audio,d.audio.frames,0)&&Throws(d.audio,0,d.audio.channels)&&Throws(d.audio,std::numeric_limits<uint64_t>::max(),0));
 CHECK(SecondsToFrames(1.5,48000)==72000&&MillisecondsToFrames(250,48000)==12000&&SecondsToFrames(-1,48000)==0&&SecondsToFrames(std::numeric_limits<double>::infinity(),48000)==0&&SecondsToFrames(static_cast<double>(std::numeric_limits<long long>::max()),1)==0);
 AudioDocument doc;CHECK(doc.State()==AudioDocumentState::Empty);doc.BeginLoad();CHECK(doc.State()==AudioDocumentState::Loading);doc.LoadLocalFile(wav);CHECK(doc.State()==AudioDocumentState::Ready);doc.LoadLocalFile(root/"missing.wav");CHECK(doc.State()==AudioDocumentState::Failed);
 std::promise<void> gateA,gateB,startedB;auto futureA=gateA.get_future().share(),futureB=gateB.get_future().share();auto fake=[&](const std::filesystem::path&p){if(p.filename()=="A")futureA.wait();else {startedB.set_value();futureB.wait();}AudioLoadResult r;r.info.path=p;r.info.frames=p.filename()=="B"?2:1;r.audio.frames=r.info.frames;return r;};AudioDocument async;{AudioLoadCoordinator load(fake);load.Begin("A",async);CHECK(async.State()==AudioDocumentState::Loading);load.Begin("B",async);startedB.get_future().wait();gateB.set_value();for(int i=0;i<100000&&!load.ApplyCompleted(async);++i)std::this_thread::yield();CHECK(async.State()==AudioDocumentState::Ready&&async.Info().frames==2);gateA.set_value();for(int i=0;i<100000;++i){load.ApplyCompleted(async);std::this_thread::yield();}CHECK(async.Info().frames==2);} std::promise<void> gateDestroy;auto destroyFuture=gateDestroy.get_future().share();AudioDocument destroyed;{AudioLoadCoordinator load([&](const std::filesystem::path&){destroyFuture.wait();return AudioLoadResult{};});load.Begin("destroy",destroyed);gateDestroy.set_value();}CHECK(destroyed.State()==AudioDocumentState::Loading);
 std::filesystem::remove_all(root,ec);return failures?1:0; }
