#include "WaveformCoordinator.h"
#include <condition_variable>
#include <mutex>
#include <optional>
#include <thread>
namespace tokkebi::audio::waveform {
struct Coordinator::SharedState { struct Job{uint64_t generation;std::shared_ptr<const DecodedPcm> pcm;};struct Result{uint64_t generation;std::shared_ptr<const PeakCache> cache;std::string diagnostic;};std::mutex mutex;std::condition_variable wake;std::optional<Job> pending;std::optional<Result> done;std::shared_ptr<const PeakCache> cache;std::string diagnostic;BuildState status=BuildState::Empty;uint64_t generation{};bool stopping=false;BuildFunction build;std::thread worker;};
Coordinator::Coordinator(BuildFunction build):m(std::make_shared<SharedState>()){m->build=build?std::move(build):[](const DecodedPcm&p,std::string*e){return BuildPeakCache(p,64,e);};auto s=m;m->worker=std::thread([s]{for(;;){SharedState::Job job;{std::unique_lock lock(s->mutex);s->wake.wait(lock,[&]{return s->stopping||s->pending.has_value();});if(s->stopping)return;job=std::move(*s->pending);s->pending.reset();}SharedState::Result result{job.generation,{},{}};try{result.cache=s->build(*job.pcm,&result.diagnostic);if(!result.cache&&result.diagnostic.empty())result.diagnostic="Peak cache build failed.";}catch(const std::bad_alloc&){result.diagnostic="Peak cache build ran out of memory.";}catch(const std::exception&e){result.diagnostic=std::string("Peak cache build failed: ")+e.what();}catch(...){result.diagnostic="Peak cache build failed unexpectedly.";}std::lock_guard lock(s->mutex);if(!s->stopping&&result.generation==s->generation)s->done=std::move(result);}});}
Coordinator::~Coordinator(){{std::lock_guard lock(m->mutex);m->stopping=true;m->pending.reset();}m->wake.notify_one();if(m->worker.joinable())m->worker.join();}
void Coordinator::Invalidate(uint64_t generation){std::lock_guard lock(m->mutex);m->generation=generation;m->cache.reset();m->done.reset();m->pending.reset();m->diagnostic.clear();m->status=BuildState::Empty;}
void Coordinator::Begin(std::shared_ptr<const DecodedPcm> pcm,uint64_t generation){std::lock_guard lock(m->mutex);m->generation=generation;m->cache.reset();m->done.reset();m->diagnostic.clear();if(!pcm){m->status=BuildState::Failed;m->diagnostic="No PCM snapshot is available.";return;}m->status=BuildState::Building;m->pending=SharedState::Job{generation,std::move(pcm)};m->wake.notify_one();}
bool Coordinator::Apply(uint64_t generation){std::lock_guard lock(m->mutex);if(!m->done||m->done->generation!=generation||generation!=m->generation)return false;m->cache=std::move(m->done->cache);m->diagnostic=std::move(m->done->diagnostic);m->status=m->cache?BuildState::Ready:BuildState::Failed;m->done.reset();return true;}
BuildState Coordinator::Status()const{std::lock_guard lock(m->mutex);return m->status;}std::shared_ptr<const PeakCache> Coordinator::Cache()const{std::lock_guard lock(m->mutex);return m->cache;}std::string Coordinator::Diagnostic()const{std::lock_guard lock(m->mutex);return m->diagnostic;}
}
