#include "Waveform.h"
#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <sstream>
namespace tokkebi::audio::waveform {
std::shared_ptr<const PeakCache> BuildPeakCache(const DecodedPcm& pcm,uint64_t base,std::string* error){ if(!pcm.channels||pcm.interleaved.size()!=pcm.frames*pcm.channels||!base){if(error)*error="Invalid PCM dimensions.";return{};} auto out=std::make_shared<PeakCache>();out->channels=pcm.channels;out->frames=pcm.frames; PeakLevel level;level.framesPerBucket=base;level.channels.resize(pcm.channels);for(uint32_t c=0;c<pcm.channels;++c)for(uint64_t first=0;first<pcm.frames;first+=base){Peak p{std::numeric_limits<float>::infinity(),-std::numeric_limits<float>::infinity(),first,std::min(pcm.frames,first+base)};for(uint64_t f=first;f<p.endFrame;++f){float v=pcm.At(f,c);if(!std::isfinite(v)){if(error)*error="Non-finite PCM.";return{};}p.minimum=std::min(p.minimum,v);p.maximum=std::max(p.maximum,v);}level.channels[c].push_back(p);}out->levels.push_back(std::move(level));while(out->levels.back().channels[0].size()>1&&out->levels.size()<24){const auto& prior=out->levels.back();PeakLevel next;next.framesPerBucket=prior.framesPerBucket*2;next.channels.resize(pcm.channels);for(uint32_t c=0;c<pcm.channels;++c)for(size_t i=0;i<prior.channels[c].size();i+=2){const auto&a=prior.channels[c][i];const auto&b=prior.channels[c][std::min(i+1,prior.channels[c].size()-1)];next.channels[c].push_back({std::min(a.minimum,b.minimum),std::max(a.maximum,b.maximum),a.firstFrame,b.endFrame});}out->levels.push_back(std::move(next));}return out;}
std::size_t ChooseLevel(const PeakCache& c,double d){size_t n=0;while(n+1<c.levels.size()&&c.levels[n+1].framesPerBucket<=d)n++;return n;}
Viewport FullViewport(uint64_t f){return {f,0,f};}
Viewport Zoom(Viewport v,double factor,double pointer,uint64_t min){if(v.Empty()||!std::isfinite(factor)||factor<=0)return v;auto span=std::max<uint64_t>(min,std::min(v.totalFrames,(uint64_t)std::llround((v.end-v.start)/factor)));pointer=std::clamp(pointer,0.,1.);auto anchor=v.start+(uint64_t)std::llround((v.end-v.start)*pointer);int64_t start=(int64_t)anchor-(int64_t)std::llround(span*pointer);start=std::clamp<int64_t>(start,0,(int64_t)(v.totalFrames-span));return {v.totalFrames,(uint64_t)start,(uint64_t)start+span};}
Viewport Scroll(Viewport v,int64_t d){if(v.Empty())return v;auto span=v.end-v.start;auto s=std::clamp<int64_t>((int64_t)v.start+d,0,(int64_t)(v.totalFrames-span));return{v.totalFrames,(uint64_t)s,(uint64_t)s+span};}
double FrameToX(const Viewport&v,uint64_t f,double w){if(v.Empty()||w<=0)return 0;return std::clamp((double)((int64_t)f-(int64_t)v.start)/(double)(v.end-v.start)*w,0.,w);} uint64_t XToFrame(const Viewport&v,double x,double w){if(v.Empty()||w<=0||!std::isfinite(x))return v.start;return v.start+(uint64_t)std::llround(std::clamp(x/w,0.,1.)*(v.end-v.start));}
std::vector<RenderColumn> BuildRenderPlan(const PeakCache&c,const Viewport&v,uint32_t width){std::vector<RenderColumn>r;if(!width||v.Empty()||c.levels.empty())return r;const auto&l=c.levels[ChooseLevel(c,(double)(v.end-v.start)/width)];for(uint32_t ch=0;ch<c.channels;++ch)for(const auto&p:l.channels[ch])if(p.endFrame>v.start&&p.firstFrame<v.end)r.push_back({FrameToX(v,p.firstFrame,width),std::clamp(p.minimum,-1.f,1.f),std::clamp(p.maximum,-1.f,1.f),ch,p.firstFrame,p.endFrame});return r;}
std::string FormatTime(uint64_t f,uint32_t r){uint64_t ms=r?(f*1000)/r:0,h=ms/3600000;ms%=3600000;std::ostringstream o;o<<std::setfill('0')<<std::setw(2)<<h<<':'<<std::setw(2)<<ms/60000<<':'<<std::setw(2)<<(ms/1000)%60<<'.'<<std::setw(3)<<ms%1000;return o.str();}
}
