if(NOT DEFINED PROJECT_SOURCE_DIR)
  message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()
set(manifest "${PROJECT_SOURCE_DIR}/assets/fonts/manifest.json")
if(NOT EXISTS "${manifest}")
  message(FATAL_ERROR "Font manifest is missing: ${manifest}")
endif()
file(READ "${manifest}" contents)
set(font_paths
  "assets/fonts/dunggeunmo/dunggeunmo.ttf|3f184d949149f2e7e6a853593e25161fb1d3b6d3708ebf79ce78600788fdea30|third_party/licenses/fonts/DungGeunMo-Public-Domain.txt"
  "assets/fonts/ridibatang/ridibatang.otf|f13a49c0815d254ac15e392953a0b056613dec08ceb378e54eeed14c4fda9a54|third_party/licenses/fonts/RIDIBatang-OFL-1.1.txt"
  "assets/fonts/galmuri/galmuri11-bitmap-regular-2.40.4.ttf|0d7e7e8652d8cf666c4501b1dfe8d4ccaee97f068edff4cc4e90f14266ed4a49|third_party/licenses/fonts/Galmuri-OFL-1.1.txt"
)
foreach(record IN LISTS font_paths)
  string(REPLACE "|" ";" fields "${record}")
  list(GET fields 0 path)
  list(GET fields 1 expected_hash)
  list(GET fields 2 license)
  if(path MATCHES "^[A-Za-z]:|^/|\\.\\.")
    message(FATAL_ERROR "Font path must stay inside the repository: ${path}")
  endif()
  if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${path}" OR NOT EXISTS "${PROJECT_SOURCE_DIR}/${license}")
    message(FATAL_ERROR "Required font or license is missing: ${path}")
  endif()
  file(SIZE "${PROJECT_SOURCE_DIR}/${path}" size)
  file(SHA256 "${PROJECT_SOURCE_DIR}/${path}" actual_hash)
  string(TOLOWER "${actual_hash}" actual_hash)
  if(size EQUAL 0 OR NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Font integrity mismatch: ${path}")
  endif()
  if(NOT contents MATCHES "${path}")
    message(FATAL_ERROR "Font manifest does not declare ${path}")
  endif()
endforeach()
file(GLOB_RECURSE bundled_fonts RELATIVE "${PROJECT_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}/assets/fonts/*")
foreach(asset IN LISTS bundled_fonts)
  if(asset MATCHES "\\.(ttf|otf|ttc|woff|woff2)$" AND NOT contents MATCHES "${asset}")
    message(FATAL_ERROR "Unexpected or undeclared font binary: ${asset}")
  endif()
endforeach()
