if(NOT DEFINED PROJECT_SOURCE_DIR)
  message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(READ "${PROJECT_SOURCE_DIR}/CMakeLists.txt" project_cmake)
file(READ "${PROJECT_SOURCE_DIR}/src/app/config.h" config_header)
file(READ "${PROJECT_SOURCE_DIR}/resources/main.rc" windows_resources)
file(READ "${PROJECT_SOURCE_DIR}/resources/tokkebi-macOS-Info.plist" macos_plist)
file(READ "${PROJECT_SOURCE_DIR}/resources/tokkebi-VST3-Info.plist" vst3_plist)
file(READ "${PROJECT_SOURCE_DIR}/resources/tokkebi-AU-Info.plist" au_plist)
file(READ "${PROJECT_SOURCE_DIR}/MASTER_BLUEPRINT.md" master_blueprint)

function(require_match content pattern description)
  if(NOT "${content}" MATCHES "${pattern}")
    message(FATAL_ERROR "Identity/version consistency check failed: ${description}")
  endif()
endfunction()

function(require_product_plist content identifier description)
  require_match("${content}" "<key>CFBundleExecutable</key>[ \t\r\n]*<string>tokkebi</string>" "${description}: executable")
  require_match("${content}" "<key>CFBundleName</key>[ \t\r\n]*<string>tokkebi</string>" "${description}: product name")
  require_match("${content}" "<key>CFBundleIdentifier</key>[ \t\r\n]*<string>${identifier}</string>" "${description}: bundle identifier")
  require_match("${content}" "<key>CFBundleShortVersionString</key>[ \t\r\n]*<string>0\\.1\\.0</string>" "${description}: short version")
  require_match("${content}" "<key>CFBundleVersion</key>[ \t\r\n]*<string>0\\.1\\.0</string>" "${description}: bundle version")
  require_match("${content}" "<key>CFBundleSignature</key>[ \t\r\n]*<string>Tkb1</string>" "${description}: plugin ID")
endfunction()

require_match("${project_cmake}" "project\\(tokkebi VERSION 0\\.1\\.0" "CMake project must be tokkebi 0.1.0")
require_match("${project_cmake}" "FORMATS \\$\\{TOKKEBI_FORMATS\\}" "CMake must use the platform target list")
require_match("${master_blueprint}" "^# tokkebi" "MASTER_BLUEPRINT.md title must be lowercase '# tokkebi'")
require_match("${config_header}" "PLUG_NAME \"tokkebi\"" "iPlug2 product name must be lowercase tokkebi")
require_match("${config_header}" "PLUG_VERSION_HEX 0x00000100" "iPlug2 packed version must be 0x00000100")
require_match("${config_header}" "PLUG_VERSION_STR \"0\\.1\\.0\"" "iPlug2 version string must be 0.1.0")
require_match("${config_header}" "PLUG_UNIQUE_ID 'Tkb1'" "iPlug2 plugin ID must remain Tkb1")
require_match("${config_header}" "PLUG_MFR_ID 'NYN1'" "iPlug2 manufacturer ID must remain NYN1")
require_match("${config_header}" "PLUG_URL_STR \"https://github\\.com/nowyoullnever/tokkebi\"" "repository URL must be current")
require_match("${config_header}" "#define PLUG_CHANNEL_IO \"0-2\"" "Standalone bus topology must remain input-free")
require_match("${config_header}" "#define PLUG_CHANNEL_IO \"2-2\"" "plugin bus topology must remain pass-through")
require_match("${windows_resources}" "VALUE \"ProductName\", \"tokkebi\"" "Windows product name must be tokkebi")
require_match("${windows_resources}" "VALUE \"FileVersion\", \"0\\.1\\.0\"" "Windows file version must be 0.1.0")

require_product_plist("${macos_plist}" "com.nowyoullnever.tokkebi" "macOS app plist")
require_product_plist("${vst3_plist}" "com.nowyoullnever.vst3.tokkebi" "VST3 plist")
require_product_plist("${au_plist}" "com.nowyoullnever.audiounit.tokkebi" "AU plist")
require_match("${au_plist}" "<key>manufacturer</key>[ \t\r\n]*<string>NYN1</string>" "AU manufacturer ID must be NYN1")
require_match("${au_plist}" "<key>subtype</key>[ \t\r\n]*<string>Tkb1</string>" "AU subtype must be Tkb1")
require_match("${au_plist}" "<key>type</key>[ \t\r\n]*<string>aufx</string>" "AU must remain an effect")

set(text_file_extensions
  .md .txt .cmake .cpp .cc .c .h .hpp .plist .rc .ps1 .yml .yaml .json .xml
)
set(text_file_names CMakeLists.txt AGENTS.md)
set(identity_validator_implementation_files
  cmake/VerifyVersion.cmake
  cmake/VerifyVersionSelfTest.cmake
)

file(GLOB_RECURSE project_files LIST_DIRECTORIES FALSE RELATIVE "${PROJECT_SOURCE_DIR}" "${PROJECT_SOURCE_DIR}/*")
foreach(project_file IN LISTS project_files)
  if(project_file MATCHES "(^|/)(\\.git|third_party|build[^/]*|out|dist|CMakeFiles|\\.vs|\\.idea|__pycache__|node_modules)(/|$)")
    continue()
  endif()

  list(FIND identity_validator_implementation_files "${project_file}" validator_implementation_index)
  if(NOT validator_implementation_index EQUAL -1)
    continue()
  endif()

  get_filename_component(project_file_name "${project_file}" NAME)
  get_filename_component(project_file_extension "${project_file}" LAST_EXT)
  string(TOLOWER "${project_file_extension}" project_file_extension)
  list(FIND text_file_extensions "${project_file_extension}" text_extension_index)
  list(FIND text_file_names "${project_file_name}" text_name_index)
  if(text_extension_index EQUAL -1 AND text_name_index EQUAL -1)
    continue()
  endif()

  file(READ "${PROJECT_SOURCE_DIR}/${project_file}" file_contents)
  string(TOLOWER "${file_contents}" normalized_file_contents)
  if(normalized_file_contents MATCHES "samplegrabber|now-you-ll-never")
    message(FATAL_ERROR "Obsolete active product identifier found in allowed text file: ${project_file}")
  endif()
endforeach()
