if(NOT DEFINED PROJECT_SOURCE_DIR)
  message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

file(REAL_PATH "${PROJECT_SOURCE_DIR}" repository_root)
set(manifest "${repository_root}/assets/fonts/manifest.json")
if(NOT EXISTS "${manifest}")
  message(FATAL_ERROR "Font manifest is missing: ${manifest}")
endif()

function(require_repository_path value field output_variable)
  if("${value}" STREQUAL "" OR "${value}" MATCHES "^[A-Za-z]:|^/|^~|\\\\|(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "${field} must be a non-empty repository-relative path: ${value}")
  endif()
  file(REAL_PATH "${repository_root}/${value}" resolved_path)
  file(RELATIVE_PATH relative_path "${repository_root}" "${resolved_path}")
  if(relative_path MATCHES "^\\.\\.(/|$)")
    message(FATAL_ERROR "${field} escapes the repository: ${value}")
  endif()
  set(${output_variable} "${resolved_path}" PARENT_SCOPE)
endfunction()

file(READ "${manifest}" manifest_contents)
string(JSON font_count ERROR_VARIABLE json_error LENGTH "${manifest_contents}" fonts)
if(NOT json_error STREQUAL "NOTFOUND")
  message(FATAL_ERROR "Font manifest must contain a fonts array: ${json_error}")
endif()
if(font_count EQUAL 0)
  message(FATAL_ERROR "Font manifest must declare at least one font")
endif()

set(declared_paths)
set(declared_ids)
math(EXPR last_index "${font_count} - 1")
foreach(index RANGE ${last_index})
  foreach(field IN ITEMS id path sha256 licensePath)
    string(JSON ${field} ERROR_VARIABLE field_error GET "${manifest_contents}" fonts ${index} ${field})
    if(NOT field_error STREQUAL "NOTFOUND" OR "${${field}}" STREQUAL "")
      message(FATAL_ERROR "Font manifest entry ${index} has no valid ${field}")
    endif()
  endforeach()

  list(FIND declared_ids "${id}" duplicate_id_index)
  if(NOT duplicate_id_index EQUAL -1)
    message(FATAL_ERROR "Duplicate font id in manifest: ${id}")
  endif()
  list(APPEND declared_ids "${id}")
  string(LENGTH "${sha256}" sha256_length)
  if(NOT sha256_length EQUAL 64 OR NOT sha256 MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Font manifest entry ${id} has an invalid lowercase SHA-256: ${sha256}")
  endif()

  require_repository_path("${path}" "Font path for ${id}" resolved_font_path)
  require_repository_path("${licensePath}" "License path for ${id}" resolved_license_path)
  if(NOT EXISTS "${resolved_font_path}")
    message(FATAL_ERROR "Declared font is missing: ${path}")
  endif()
  if(NOT EXISTS "${resolved_license_path}" OR IS_DIRECTORY "${resolved_license_path}")
    message(FATAL_ERROR "Declared font license is missing: ${licensePath}")
  endif()
  file(SHA256 "${resolved_font_path}" actual_hash)
  string(TOLOWER "${actual_hash}" actual_hash)
  if(NOT actual_hash STREQUAL sha256)
    message(FATAL_ERROR "Font integrity mismatch for ${id}: ${path}")
  endif()
  list(APPEND declared_paths "${path}")
endforeach()

file(GLOB_RECURSE repository_fonts RELATIVE "${repository_root}" "${repository_root}/assets/fonts/*")
foreach(asset IN LISTS repository_fonts)
  string(TOLOWER "${asset}" lowercase_asset)
  if(lowercase_asset MATCHES "\\.(ttf|otf|ttc|eot|woff|woff2)$")
    list(FIND declared_paths "${asset}" declared_asset_index)
    if(declared_asset_index EQUAL -1)
      message(FATAL_ERROR "Unexpected or undeclared font binary: ${asset}")
    endif()
  endif()
endforeach()
